### ISSUE TITLE
SvelteKit wizard returns TimeoutError

### ISSUE THREAD

**Issue by michaelchai-sentry** [getsentry/sentry-wizard#555] opened 2024-03-29 21:41 UTC
### Environment

One of our customers reported that they get a TimeoutError when they try to use the SvelteKit wizard to set up a new project

### Steps to Reproduce

1. Use SvelteKit wizard
2. Select that you already have a Sentry account
3. Try to log into sentry.io with the link provided by the wizard

### Expected Result

Continue the setup through the wizard

### Actual Result

Get the Server Error page (screenshot)
<img width="1112" alt="Screenshot 2024-03-29 at 2 40 49 PM" src="https://github.com/getsentry/sentry-wizard/assets/98921471/45ab7b4e-0b29-4443-9296-319bad07f50c">

**Comment by Lms24** [comment] 2024-04-02 07:55
Hey @michaelchai-sentry I just tried running the SvelteKit wizard. Once with already being logged in before starting the wizard and once with logging in within the wizard flow. In both cases, I couldn't reproduce this error. Do you have any more insights into the customer's network setup? Usually, we get errors in this step when users have network issues or block certain requests. However in this case, it looks like there might be an error within the Sentry application. Any chance this happened during an incident?

**Comment by AbhiPrasad** [comment] 2024-04-02 21:05
@Lms24 this is the following sentry error: https://sentry.sentry.io/auth/login/sentry/?next=%2Fissues%2F4974702451%2Fevents%2Faa4c48000beb432a8741b56d0652c807%2F%3Fproject%3D1

From slack: https://sentry.slack.com/archives/C05LTSKSG6T/p1711477829219289

> The wizard pulls all projects and for a big org like __REMOVED__ it takes too much time to read all the rows and turn them into a response. The solution for sdk-wizard would be to limit the results we fetch. We had that in place before but sdk-wizard folks asked that those limits be removed. Putting the limits back could be a path forward.

**Comment by andreiborza** [comment] 2024-12-10 10:55
Closing this as the wizard does no longer. fetch a list of projects, the project selection happens in the newly opened browser window.

**Closed by andreiborza** 2024-12-10 10:55 UTC
