### ISSUE TITLE
Wizard hangs when running `npx @sentry/wizard@latest -i sourcemaps`

### ISSUE THREAD

**Issue by off99555** [getsentry/sentry-wizard#523] opened 2024-01-09 08:39 UTC
### Environment

Running Sentry Wizard...
version: 3.20.1 | sentry-cli version: 1.77.1
Windows 11

### Steps to Reproduce

1. Run `npx @sentry/wizard@latest -i sourcemaps` on a Remix project
2. Answer some questions e.g. use sentry.io, I have sentry account, select your project.
3. You will not be able to select your framework with keyboard arrow keys.
### Expected Result

When I see the question "Which framework, bundler or build tool are you using?", I should be able to select my framework by pressing my keyboard arrow keys.

### Actual Result

When I see the question "Which framework, bundler or build tool are you using?", I cannot move my cursor using keyboard arrows. The app appears to freeze. I can't do Ctrl+C to quit it either. I can only press Enter to accept the currently highlighted framework (which is `tsc`).
<img width="796" alt="image" src="https://github.com/getsentry/sentry-wizard/assets/15215732/902b152a-4f35-47a0-937f-48b2378f2dcd">

**Comment by Lms24** [comment] 2024-01-09 09:57
Hi @off99555 thanks for writing in!

This issue is a duplicate of #492 - I'm gonna close it. Please feel free to follow and comment in #492 instead. 

Side note: There's already a suggested fix for `clack`, the underlying library we use for generating these prompts. Seems like it wasn't yet fixed or released. We might have to vendor in the fix ourselves.

**Closed by Lms24** 2024-01-09 09:57 UTC
Labels: Waiting for: Product Owner
