### ISSUE TITLE
Cannot find module '@babel/parser'

### ISSUE THREAD

**Issue by vaynevayne** [getsentry/sentry-wizard#660] opened 2024-09-04 10:14 UTC
### Environment

What version are you running? Etc.

### Steps to Reproduce

1.  npx @sentry/wizard@latest -i sourcemaps      

### Expected Result

What you thought would happen.

### Actual Result

node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module '@babel/parser'
Require stack:
- /Users/xiaofan_yu/.npm/_npx/ddb126e78325956c/node_modules/magicast/dist/index.cjs
- /Users/xiaofan_yu/.npm/_npx/ddb126e78325956c/node_modules/@sentry/wizard/dist/src/react-native/metro.js
- /Users/xiaofan_yu/.npm/_npx/ddb126e78325956c/node_modules/@sentry/wizard/dist/src/react-native/uninstall.js
- /Users/xiaofan_yu/.npm/_npx/ddb126e78325956c/node_modules/@sentry/wizard/dist/src/react-native/react-native-wizard.js
- /Users/xiaofan_yu/.npm/_npx/ddb126e78325956c/node_modules/@sentry/wizard/dist/src/run.js
- /Users/xiaofan_yu/.npm/_npx/ddb126e78325956c/node_modules/@sentry/wizard/dist/bin.js

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by Lms24** [comment] 2024-09-05 14:14
Hi, I cannot reproduce this on my end.

Please let me know your Node version, OS and ideally provide a minimal reproduction that we can use to debug this further. Thank you!

**Comment by Lms24** [comment] 2024-09-05 14:17
Moreover, if I simply `npm install @senrtry/wizard` (you shouldn't need to do this but perhaps it's worth a try), `@babel/parser` is getting installed. `magicast` lists it as a dependency so I'm suspecting some kind of stale `node_modules` folder or some other kind of dependency resolution problem.

**Comment by vaynevayne** [comment] 2024-09-06 01:32
Strange problem, I manually installed the babelparse process after I

**Comment by Lms24** [comment] 2024-09-06 08:05
Sorry but this issue is unactionable. Closing for now. If the problem persists, please let me know with all the details I asked for and a reproduction. Thanks!

**Closed by Lms24** 2024-09-06 08:05 UTC
Labels: Waiting for: Product Owner
