### ISSUE TITLE
Sentry Wizard can't work with Android project config file format: build.gradle.kts

### ISSUE THREAD

**Issue by Kyborg2011** [getsentry/sentry-wizard#714] opened 2024-11-17 16:14 UTC
### Environment

Sentry Wizard v3.34.4 on Fedora Linux 41

### Steps to Reproduce

I have run a sentry-wizard in a folder with an Android project with a config file build.gradle.kts (not a build.gradle) - it is a convenient Kotlin configuration file and in general right now in official Android docs this format of gradle config is more preferable than simple build.gradle. 

### Expected Result

Sentry-wizard must find an app's directory (current dir in shell) and catch a build.gradle.kts as a normal configuration file of a project.

### Actual Result

"Unable to find your app's directory.
Please enter the relative path to your app's build.gradle file from the root project"

**Comment by andreiborza** [comment] 2024-11-19 08:37
Hi @Kyborg2011, thanks for filing this. 

Looking through our wizard code, it looks like we do support `build.gradle.kts` files 🤔. Do you have a small reproduction repo where we can investigate your issue further?

**Comment by AbhiPrasad** [comment] 2024-12-09 16:14
Closing this issue for cleanup. @Kyborg2011 if this still applies, could you share a reproduction app like @andreiborza asked for above? Thanks!

**Closed by AbhiPrasad** 2024-12-09 16:14 UTC
