### ISSUE TITLE
Wizard panicing in vite to next migrated project

### ISSUE THREAD

**Issue by Gregoor** [getsentry/sentry-wizard#563] opened 2024-04-19 12:28 UTC
Unfortunately I can't share the repo as it's private and I have not created a minimal repro yet.

### Environment

MacOS 14.4

### Steps to Reproduce

1. Start a vite project
2. Migrate it to next using their guide
3. `pnpx @sentry/wizard@latest --debug -i nextjs`

### Actual Result

```
Sentry Wizard failed with:
TypeError: Cannot read properties of null (reading 'token')
    at /Users/gregor/Library/pnpm/store/v3/tmp/dlx-47042/node_modules/.pnpm/@sentry+wizard@3.22.0/node_modules/@sentry/wizard/dist/src/utils/clack-utils.js:744:48
    at step (/Users/gregor/Library/pnpm/store/v3/tmp/dlx-47042/node_modules/.pnpm/@sentry+wizard@3.22.0/node_modules/@sentry/wizard/dist/src/utils/clack-utils.js:56:23)
    at Object.next (/Users/gregor/Library/pnpm/store/v3/tmp/dlx-47042/node_modules/.pnpm/@sentry+wizard@3.22.0/node_modules/@sentry/wizard/dist/src/utils/clack-utils.js:37:53)
    at fulfilled (/Users/gregor/Library/pnpm/store/v3/tmp/dlx-47042/node_modules/.pnpm/@sentry+wizard@3.22.0/node_modules/@sentry/wizard/dist/src/utils/clack-utils.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I'm assuming it's this line:

https://github.com/getsentry/sentry-wizard/blob/4c159d9096dc5d22b30c92949b64201faf7c5593/src/utils/clack-utils.ts#L791

**Comment by mlecoq** [comment] 2024-04-19 17:56
I have the same issue on a classic nextjs project, doesn't seem to be related to vite

**Comment by Lms24** [comment] 2024-04-22 07:30
Hey @mlecoq thanks for reporting! I can reproduce this myself. Will investigate ASAP

**Comment by Lms24** [comment] 2024-04-22 08:04
First update:
* We tracked this down to a Sentry API Endpoint related problem. We're working on a fix right now.
* This issue seems to affect only users who are part of more than one organization in Sentry. 
* Unfortunately, the only **workaround** for affected users at the time being is to follow our **"Manual Setup" guide** for 
  * [NextJS](https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/)
  * [SvelteKit](https://docs.sentry.io/platforms/javascript/guides/sveltekit/manual-setup/)
  * [Remix](https://docs.sentry.io/platforms/javascript/guides/remix/manual-setup/)
  * [React Native](https://docs.sentry.io/platforms/react-native/manual-setup/)
  * [Android](https://docs.sentry.io/platforms/android/manual-setup/)
  * [iOS](https://docs.sentry.io/platforms/apple/guides/ios/manual-setup/)
  * If you're trying to setup source maps via the wizard (`npx @sentry/wizard -i sourcemaps`), please follow the guides for your respective platform how to configure sourcemaps. ([Example link for plain browser JS](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/))

**Comment by Lms24** [comment] 2024-04-22 09:52
Update: We tracked the issue down to a change that makes re-using an already created user-based auth token no longer possible. Turns out, our wizard endpoint relied on this logic and we missed it when we made the change. Opened a PR (https://github.com/getsentry/sentry/pull/69388) to fix. The fix should be live in the next couple of hours. Will let you know when we're there.

**Comment by mlecoq** [comment] 2024-04-22 09:58
Thanks a lot !

**Comment by Lms24** [comment] 2024-04-22 12:26
Final update: We deployed the fix and I can no longer reproduce the issue 🎉 

Closing as I'm fairly certain the issue is resolved. Please let me know if you're still experiencing problems! Also, apologies again for the inconvenience! We'll follow up with some improvements, both in the wizard as well as the Sentry backend to better prevent this in the future.

**Closed by Lms24** 2024-04-22 12:26 UTC

**Comment by mlecoq** [comment] 2024-04-22 12:48
I confirm that it's fixed !
