### ISSUE TITLE
Loading Wizard failed. Please try again in a few minutes and let us know if this issue persists

### ISSUE THREAD

**Issue by zhutoutoutousan** [getsentry/sentry-wizard#405] opened 2023-08-26 15:26 UTC
### Environment

Node Version: v18.14.0
Windows 11 22H2

### Steps to Reproduce

1. Use `turborepo` to create a package based monorepo with pnpm workspace as manager
2. Follow the official sentry nextjs pendo, execute `npx @sentry/wizard -i nextjs --debug` in {TURBOREPO_PATH}/app/{DESIRED_APP_PATH}/ where `package.json` resides

### Expected Result

`Loading Wizard` should succeed and life should be right as rain 🍡 

### Actual Result
```
PS {DESIRED_APP_PATH}> npx @sentry/wizard -i nextjs --debug
Need to install the following packages:
  @sentry/wizard@3.10.0
Ok to proceed? (y) Y
{
        "_": [],
        "i": "nextjs",
        "integration": "nextjs",
        "debug": true,
        "uninstall": false,
        "skip-connect": false,
        "skipConnect": false,
        "quiet": false,
        "s": false,
        "signup": false,
        "disable-telemetry": false,
        "disableTelemetry": false,
        "$0": "C:\\Users\\Administrator\\AppData\\Local\\npm-cache\\_npx\\a8388072043b4cbc\\node_modules\\@sentry\\wizard\\dist\\bin.js"
}
Running Sentry Wizard...
version: 3.10.0 | sentry-cli version: 1.75.2
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)
Skipping connection to Sentry due files already patched

{
        "integration": {
                "_argv": {
                        "_": [],
                        "i": "nextjs",
                        "integration": "nextjs",
                        "debug": true,
                        "uninstall": false,
                        "skip-connect": false,
                        "skipConnect": false,
                        "quiet": false,
                        "s": false,
                        "signup": false,
                        "disable-telemetry": false,
                        "disableTelemetry": false,
                        "$0": "C:\\Users\\Administrator\\AppData\\Local\\npm-cache\\_npx\\a8388072043b4cbc\\node_modules\\@sentry\\wizard\\dist\\bin.js"
                },
                "_isDebug": true
        }
}


{
        "integration": {
                "_argv": {
                        "_": [],
                        "i": "nextjs",
                        "integration": "nextjs",
                        "debug": true,
                        "uninstall": false,
                        "skip-connect": false,
                        "skipConnect": false,
                        "quiet": false,
                        "s": false,
                        "signup": false,
                        "disable-telemetry": false,
                        "disableTelemetry": false,
                        "$0": "C:\\Users\\Administrator\\AppData\\Local\\npm-cache\\_npx\\a8388072043b4cbc\\node_modules\\@sentry\\wizard\\dist\\bin.js"
                },
                "_isDebug": true
        }
}


┌   Sentry Next.js Wizard 
│
◇   ──────────────────────────────────────────────────────────────╮
│                                                                 │
│  This Wizard will help you set up Sentry for your application.  │
│  Thank you for using Sentry :)                                  │
│                                                                 │
│  Version: 3.10.0                                                │
│                                                                 │
├─────────────────────────────────────────────────────────────────╯
│
◇  Are you using Sentry SaaS or self-hosted Sentry?
│  Sentry SaaS (sentry.io)
│
◇  Do you already have a Sentry account?
│  Yes
│
■  Loading Wizard failed.
│
└  Please try again in a few minutes and let us know if this issue persists: https://github.com/getsentry/sentry-wizard/issues
```

**Comment by Lms24** [comment] 2023-08-26 19:00
Hi @zhutoutoutousan 

this message appears if an Http request to sentry.io fails. You can try running 

```sh
 curl https://sentry.io/api/0/wizard/
```

and see if if you get a resonse similar to 
```
{"hash":"<hash value>"}
```

**Comment by Lms24** [comment] 2023-08-30 09:43
Please let us know if, after trying the `curl` command, you still have this problem.

**Comment by iArchin** [comment] 2023-10-10 14:33
I also have the same problem with React Native project

**Comment by Lms24** [comment] 2023-10-10 14:50
Hi @iArchin can you share a reproducible example? For instance, the exact parameters with which you called the wizard? Does this happen with the latest wizard version?

**Comment by Lms24** [comment] 2023-10-10 15:17
I tried reproducing this and for me, things load fine: 
![image](https://github.com/getsentry/sentry-wizard/assets/8420481/6e82a4d4-fafd-4a62-897f-5b0e0fd29ef1)


Have you tried the `curl` command I posted in my initial reply?

**Comment by drop0118** [comment] 2024-01-09 06:09
I tried `curl` but get `Loading Wizard failed.` again.

<img width="826" alt="image" src="https://github.com/getsentry/sentry-wizard/assets/3488084/c6b6dbf7-56a4-4e10-9dbc-04d5fe7f4aca">

**Comment by Lms24** [comment] 2024-01-10 10:16
Hmm Honestly, I'm not sure what's going on here. Querying the `api/0/wizard/` endpoint via `curl` seems to work while [querying the exact same endpoint](https://github.com/getsentry/sentry-wizard/blob/2bca6a25f4957721bbcf426815cb2884455d4ef4/src/utils/clack-utils.ts#L892) doesn't work in the wizard.

Sorry for the naive question but does this always happen or was it a one-of?

**Comment by barghi** [comment] 2024-01-10 11:16
> I tried `curl` but get `Loading Wizard failed.` again.
> 
> <img alt="image" width="826" src="https://private-user-images.githubusercontent.com/3488084/295115112-c6b6dbf7-56a4-4e10-9dbc-04d5fe7f4aca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODU2MDQsIm5iZiI6MTcwNDg4NTMwNCwicGF0aCI6Ii8zNDg4MDg0LzI5NTExNTExMi1jNmI2ZGJmNy01NmE0LTRlMTAtOWRiYy0wNGQ1ZmU3ZjRhY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMTExNTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTE4ZTg5MjEwNDY4OTZmNDg4MGQ5ZjM5MmI3N2U2M2FlMmY4Yzk5YjFhMzk0OGY5MTZmN2NmMDA5YzBmYjBlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LBKhm-vqpkpuSRAOq8OhJBqLNbOoyUIWdN2w04rh0V8">

I am facing this issue too

**Comment by drop0118** [comment] 2024-01-10 11:19
> Hmm Honestly, I'm not sure what's going on here. Querying the `api/0/wizard/` endpoint via `curl` seems to work while [querying the exact same endpoint](https://github.com/getsentry/sentry-wizard/blob/2bca6a25f4957721bbcf426815cb2884455d4ef4/src/utils/clack-utils.ts#L892) doesn't work in the wizard.
> 
> Sorry for the naive question but does this always happen or was it a one-of?

Always happened.

**Comment by Lms24** [comment] 2024-01-10 13:59
Hi @barghi and @drop0118 - we just released a new version of the wizard which will log out more details of the error/reason why this request is failing for you. Please run the wizard again (make sure to use `@sentry/wizard@latest`) and paste the log output here. It's not an ideal way of debugging but I can't reproduce this at all on my end. thank you!

**Comment by drop0118** [comment] 2024-01-10 19:03
> Hi @barghi and @drop0118 - we just released a new version of the wizard which will log out more details of the error/reason why this request is failing for you. Please run the wizard again (make sure to use `@sentry/wizard@latest`) and paste the log output here. It's not an ideal way of debugging but I can't reproduce this at all on my end. thank you!

<img width="1438" alt="image" src="https://github.com/getsentry/sentry-wizard/assets/3488084/96793bf5-ffe6-4b05-b895-7e2bdcedfada">

**Comment by Lms24** [comment] 2024-01-12 09:43
Hey @barghi and @drop0118, I tried replacing our request library `axios` with `node-fetch` to see if there's a difference. Maybe Axios is adding something to the request that makes us or some party in between block it. This is not yet released as a stable version but as a beta because I want to see if it changes anything at all. So to run this, please run

```sh
npx @sentry/wizard@3.20.3-beta.0
``` 

please let me know about the result, thanks!

**Comment by Lms24** [comment] 2024-01-19 09:27
thanks for confirming! 

@drop0118 since you were also affected - would you mind confirming the beta version fixes the issue for you too?

**Comment by St-coder** [comment] 2024-01-31 09:46
me too; 
fix this bug,please!

**Comment by Lms24** [comment] 2024-01-31 09:51
@St-coder  I'm rarely getting annoyed by GH users but if you wanna see a bug fixed, don't just downvote me when I outline my fix ;) For instance, you could let me know if running the beta fixed the issue for you.

**Comment by St-coder** [comment] 2024-02-23 03:42
> @St-coder I'm rarely getting annoyed by GH users but if you wanna see a bug fixed, don't just downvote me when I outline my fix ;) For instance, you could let me know if running the beta fixed the issue for you.

Sorry! I apologize for my behavior.
I tried the method you provided, but it still gives an error.  please help me solve it.



npx @sentry/wizard@3.20.3-beta.0
 


![image](https://github.com/getsentry/sentry-wizard/assets/16557111/c7d684de-2c4b-4cc4-88a4-87da02297fde)
![image](https://github.com/getsentry/sentry-wizard/assets/16557111/c87f1d50-31a9-41f9-b511-de38e94340ea)
![image](https://github.com/getsentry/sentry-wizard/assets/16557111/d9f999df-f0d8-47c6-86a9-38bd5c2c7d5e)

**Comment by Lms24** [comment] 2024-02-23 08:44
@St-coder no worries! Unfortunately, I still don't have a concrete idea what could be causing this difference in request behaviour. Given that the switch from `axios` to` node-fetch` (which is what I did in the beta version) also didn't help, I don't think that it's something we do wrong in the wizard in particular. You can see for yourself, we only make a simple GET request to the very same URL: https://github.com/getsentry/sentry-wizard/blob/5a5187647fc3f755b30c5044dfa60b15abd6b8ed/src/utils/clack-utils.ts#L892

My overall suspicion for all of the errors mentioned in this thread is that an entity is interfering with the request (e.g. China's firewall). I cannot tell you how to work around this but so far all the reports we have received seem to confirm this pattern.

**Comment by St-coder** [comment] 2024-02-29 05:03
> @St-coder no worries! Unfortunately, I still don't have a concrete idea what could be causing this difference in request behaviour. Given that the switch from `axios` to` node-fetch` (which is what I did in the beta version) also didn't help, I don't think that it's something we do wrong in the wizard in particular. You can see for yourself, we only make a simple GET request to the very same URL:
> 
> https://github.com/getsentry/sentry-wizard/blob/5a5187647fc3f755b30c5044dfa60b15abd6b8ed/src/utils/clack-utils.ts#L892
> 
> My overall suspicion for all of the errors mentioned in this thread is that an entity is interfering with the request (e.g. China's firewall). I cannot tell you how to work around this but so far all the reports we have received seem to confirm this pattern.

Thank you, I have found the cause. It may be due to the Chinese firewall. After taking the steps to privatize Sentry, the issue did not occur again.

Please help me close this issue. The problem has been solved. Thank you!

**Closed** 2024-02-29 09:06 UTC
Labels: Waiting for: Product Owner
